sbatch exp_baseline_LSTM.py --DATASET 0 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 1 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 2 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 3 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 4 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 5 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 6 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 7 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 8 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 9 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 10 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 11 --task temporized --projectname Baseline
sbatch exp_baseline_LSTM.py --DATASET 12 --task temporized --projectname Baseline
