sbatch exp_pSNN.py --DATASET 00 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 00 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 00 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 00 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 12 --SEED 9 --projectname pSNN