sbatch exp_pSNN.py --DATASET 01 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 01 --SEED 9 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 02 --SEED 9 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 03 --SEED 9 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 04 --SEED 9 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 05 --SEED 9 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 06 --SEED 9 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 0 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 1 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 2 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 3 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 4 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 5 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 6 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 7 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 8 --DEVICE cpu --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 9 --DEVICE cpu --projectname pSNN