sbatch exp_pSNN.py --DATASET 07 --SEED 0 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 07 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 0 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 08 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 0 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 09 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 0 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 10 --SEED 9 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 0 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 1 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 2 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 3 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 4 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 5 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 6 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 7 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 8 --projectname pSNN
sbatch exp_pSNN.py --DATASET 11 --SEED 9 --projectname pSNN