sbatch baseline_SNN.py 0
sbatch baseline_SNN.py 1
sbatch baseline_SNN.py 2
sbatch baseline_SNN.py 3
sbatch baseline_SNN.py 4
sbatch baseline_SNN.py 5
sbatch baseline_SNN.py 6
sbatch baseline_SNN.py 7
sbatch baseline_SNN.py 8
sbatch baseline_SNN.py 9
sbatch baseline_SNN.py 10
sbatch baseline_SNN.py 11
sbatch baseline_SNN.py 12
sbatch baseline_SNN.py 13
sbatch baseline_SNN.py 14
sbatch baseline_SNN.py 15
sbatch baseline_SNN.py 16
sbatch baseline_SNN.py 17
sbatch baseline_SNN.py 18
sbatch baseline_SNN.py 19
sbatch baseline_SNN.py 20
sbatch baseline_SNN.py 21
sbatch baseline_SNN.py 22
sbatch baseline_SNN.py 23
sbatch baseline_SNN.py 24
sbatch baseline_SNN.py 25
sbatch baseline_SNN.py 26
sbatch baseline_SNN.py 27
sbatch baseline_SNN.py 28
sbatch baseline_SNN.py 29
sbatch baseline_SNN.py 30
sbatch baseline_SNN.py 31
sbatch baseline_SNN.py 32
sbatch baseline_SNN.py 33
sbatch baseline_SNN.py 34
sbatch baseline_SNN.py 35
sbatch baseline_SNN.py 36
sbatch baseline_SNN.py 37
sbatch baseline_SNN.py 38
sbatch baseline_SNN.py 39
sbatch baseline_SNN.py 40
sbatch baseline_SNN.py 41
sbatch baseline_SNN.py 42
sbatch baseline_SNN.py 43
sbatch baseline_SNN.py 44
sbatch baseline_SNN.py 45
sbatch baseline_SNN.py 46
sbatch baseline_SNN.py 47
sbatch baseline_SNN.py 48
sbatch baseline_SNN.py 49
