sbatch baseline_MLP.py 0
sbatch baseline_MLP.py 1
sbatch baseline_MLP.py 2
sbatch baseline_MLP.py 3
sbatch baseline_MLP.py 4
sbatch baseline_MLP.py 5
sbatch baseline_MLP.py 6
sbatch baseline_MLP.py 7
sbatch baseline_MLP.py 8
sbatch baseline_MLP.py 9
