sbatch baseline_LSTM.py 0
sbatch baseline_LSTM.py 1
sbatch baseline_LSTM.py 2
sbatch baseline_LSTM.py 3
sbatch baseline_LSTM.py 4
sbatch baseline_LSTM.py 5
sbatch baseline_LSTM.py 6
sbatch baseline_LSTM.py 7
sbatch baseline_LSTM.py 8
sbatch baseline_LSTM.py 9
